//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Buy
    {
        
        public int orderid { get; set; }
        
        public string Name { get; set; }
        
        public Nullable<int> Price { get; set; }
       
        public Nullable<int> Quantity { get; set; }
       
        public Nullable<int> Id { get; set; }
       
        public Nullable<System.DateTime> BuyDate { get; set; }
    
        public virtual Pet Pet { get; set; }
    }
}
